name: flutter_search_bar
description: A (mostly) automatic search bar inside an AppBar for flutter
version: 2.0.4
homepage: https://frozor.io
author: Spencer <spencer@frozor.io>

environment:
  sdk: "^2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any

flutter:
  uses-material-design: true

dev_dependencies:
  test: any
